export const ALL_BIRDS = [
    'Purple Finch',
    'House Finch',
    'Varied Bunting',
    'Chestnut-Backed Chickadee',
    'White-Crowned Sparrow',
    'Mountain Chickadee',
    'Juniper Titmouse',
    'American Robin',
    'Rose-Ringed Parakeet',
    'Black-Billed Magpie',
    'Stellers Jay',
    'Dark-Eyed Junco',
    'Song Sparrow',
    'California Towhee',
    'Spotted Towhee',
    'Golden-Crowned Sparrow',
    'California Quail',
    'Bushtit',
    'Java Sparrow',
    'Brown Creeper',
    'Black-Capped Chickadee',
    'Saffron Finch',
    'African Silverbill',
    'House Sparrow',
    'Hawfinch',
    'Common Reed Bunting',
    'European Robin',
    'Evening Grosbeak',
    'Indigo Bunting',
    'Feral Pigeon',
    'Blue Jay',
    'Rose-Breasted Grosbeak',
    'American Crow',
    'Mourning Dove',
    'Northern Flicker',
    'Northern Cardinal',
    'Tufted Titmouse',
    'Pileated Woodpecker',
    'White-Throated Sparrow',
    'White-Breasted Nuthatch',
    'Red-Winged Blackbird',
    'American Goldfinch',
    'Eastern Towhee',
    'Pine Warbler',
    'Field Sparrow',
    'Downy Woodpecker',
    'Gray Catbird',
    'Fish Crow',
    'Brown-Headed Cowbird',
    'Carolina Wren',
    'Common Grackle',
    'Swamp Sparrow',
    'Orchard Oriole',
    'Common Starling',
    'Eastern Bluebird',
    'Hummingbird',
    'White-Winged Dove',
    'Red-Bellied Woodpecker',
    'Golden-Crowned Kinglet',
    'Hairy Woodpecker',
    'Canada Jay',
    'Red-Headed Woodpecker',
    'Yellow-Bellied Sapsucker',
    'Eurasian Collared Dove',
    'Scarlet Tanager',
    'Painted Bunting',
    'Pigeon',
    'Chipping Sparrow',
    'Cedar Waxwing',
    'Carolina Chickadee',
    'Pine Siskin',
    'Summer Tanager',
    'Common Blackbird',
    'Northern Mockingbird',
    'Eurasian Jay',
    'Boreal Chickadee',
    'Red-Breasted Nuthatch',
    'Brown-Headed Nuthatch',
    'Sparrow',
    'Common Waxbill',
    'Bobolink',
    'Ramhocelus Tanager',
    'Pine Grosbeak',
    'House Wren',
    'Pyrrhuloxia',
    'Thrush',
    'Scaly-Breasted Munia',
    'Rufous-Crowned Sparrow',
    'Fox Sparrow',
    'Woodhouses Scrub-Jay',
    'Black Rosy-Finch',
    'Brown-Capped Rosy-Finch',
    'Lark Sparrow',
    'Canyon Towhee',
    'Baltimore Oriole',
    'Brown Thrasher',
    'Common Ground-Dove',
    'Cassins Finch',
    'Curve-Billed Thrasher',
    'Common Redpoll',
    'Tyrant Flycatcher',
    'Winter Wren',
    'Ladder-Backed Woodpecker',
    'Bohemian Waxwing',
    'Blue Grosbeak',
    'Lesser Goldfinch',
    'California Scrub-Jay',
    'California Thrasher',
    'Black Redstart',
    'Red-Breasted Sapsucker',
    'Gambels Quail',
    'Mountain Bluebird',
    'Lewiss Woodpecker',
    'Pygmy Nuthatch',
    'Oak Titmouse',
    'Great Tit',
    'Hooded Crow',
    'Red Crossbill',
    'Gray-Crowned Rosy-Finch',
    'Crow',
    'Brewers Blackbird',
    'Black-Headed Grosbeak',
    'Clarks Nutcracker',
    'Gila Woodpecker',
    'Bullocks Oriole',
    'Western Tanager',
    'Pinyon Jay',
    'Hermit Thrush',
    'Wood Thrush',
    'Red-Billed Quelea',
    'Cactus Wren',
    'Hooded Oriole',
    'Verdin',
    'Hepatic Tanager',
    'New World Blackbird',
    'Band-Tailed Pigeon',
    'Rusty Blackbird',
    'Lazuli Bunting',
    'Chachalaca',
    'Lincolns Sparrow',
    'Lawrences Goldfinch',
    'Nuttalls Woodpecker',
    'Aberts Towhee',
    'Inca Dove',
    'Eurasian Nuthatch',
    'Black Woodpecker',
    'Middle Spotted Woodpecker',
    'Eurasian Tree Sparrow',
    'Common Wood Pigeon',
    'Marsh Tit',
    'Eurasian Blue Tit',
    'Mousebird',
    'Western Bluebird',
    'Eurasian Bullfinch',
    'Dark-Blue Jay',
    'Woodpecker',
    'Yellow-Throated Warbler',
    'Siskin',
    'Wren',
    'Acorn Woodpecker',
    'American Tree Sparrow',
    'European Goldfinch',
    'Bishop',
    'Cinereous Tit',
    'Ruby-Crowned Kinglet',
    'White-Headed Woodpecker',
    'Orange-Crowned Warbler',
    'Rufous-Collared Sparrow',
    'Blue-Gray Gnatcatcher',
    'Dickcissel',
    'Red-Headed Finch',
    'White-Tipped Dove',
    'Red-Cockaded Woodpecker',
    'Red-Naped Sapsucker',
    'Bronzed Cowbird',
    'Townsends Warbler',
    'Francolin',
    'Ruddy Ground Dove',
    'Grosbeak',
    'Dunnock',
    'Diuca Finch',
    'Mockingbird',
    'Clay-Colored Sparrow',
    'Crested Tit',
    'Willow Tit',
    'Eurasian Blackcap',
    'Great Spotted Woodpecker',
    'Spotted Dove',
    'Green-Tailed Towhee',
    'Scotts Oriole',
    'Red-Whiskered Bulbul',
    'Spot-Breasted Oriole',
    'Zebra Dove',
    'Great-Tailed Grackle',
    'Pacific Wren',
    'Long-Tailed Tit',
    'Fieldfare',
    'Eurasian Magpie',
    'Green Jay',
    'Yellow-Faced Grassquit',
    'Tanager',
    'Monk Parakeet',
    'Common Linnet',
    'White-Eye',
    'Clay-Colored Thrush',
    'Common Myna',
    'Brambling',
    'Great Kiskadee',
    'Short-Toed Treecreeper',
    'Flame-Colored Tanager',
    'Yellow-Headed Blackbird',
    'Parrot',
    'Western Meadowlark',
    'Cirl Bunting',
    'Pin-Tailed Whydah',
    'Eastern Meadowlark',
    'Bridled Titmouse',
    'Northern Red Bishop',
    'Bulbul',
    'Florida Scrub-Jay',
    'Starling',
    'Yellow-Billed Magpie',
    'Black-Crested Titmouse',
    'Dusky-faced Tanager',
    'White-Eared Bulbul',
    'Garden Warbler',
    'Weaver',
    'White-Spectacled Bulbul',
    'European Greenfinch',
    'Black-faced Tanager',
    'Varied Thrush',
    'Corn Bunting',
    'Laughing Dove',
    'Saltator',
    'Gilded Flicker',
    'Honeycreeper',
    'Manakin',
    'Dusky Thrush',
    'Barbet',
    'Sunbird',
    'Red-Headed Cardinal',
    'Rook',
    'Red-Vented Bulbul',
    'Red-Crested Cardinal',
    'Lavender Waxbill',
    'Red Avadavat',
    'Warbling White-Eye',
    'Yellow-Fronted Canary',
    'Coal Tit',
    'Go-away-bird',
    'Trogon',
    'House Crow',
    'Blue Mockingbird',
    'Australasian robin',
    'Cape Robin-Chat',
    'Common Chaffinch',
    'Serin',
    'Crimson Rosella',
    'Rainbow Lorikeet',
    'Australian King Parrot',
    'Superb Parrot',
    'Purple-crowned Lorikeet',
    'Eastern Rosella',
    'Sulphur-Crested Cockatoo',
    'Galah',
    'Glossy Black Cockatoo',
    'Western Corella',
    'Musk Lorikeet',
    'Italian Sparrow',
    'Pied Currawong',
    'Eurasian Siskin',
    'Gray-Headed Woodpecker',
    'European Serin',
    'Scaly-breasted Lorikeet',
    'Song Thrush',
    'White-winged chough',
    'Stock Dove',
    'Carrion Crow',
    'Western Jackdaw',
    'Goldcrest',
    'Australian Ringneck',
    'European Green Woodpecker',
    'Yellow-Tailed Black Cockatoo',
    'Pied Wagtail',
    'Mistle Thrush',
    'Spotless Starling',
    'Common Raven',
    'Redwing',
    'Lesser Spotted Woodpecker',
    'Rosy-Faced Lovebird',
    'Magpie-Lark',
    'Common Bronzewing',
    'Noisy Miner',
    'Laughing Kookaburra',
    'Australian Magpie',
    'Gray Currawang',
    'Australian Crow',
    'Little Corella',
    'Pink Cockatoo',
    'Eurasian Wren',
    'Eurasian Treecreeper',
    'Citril Finch',
    'Golden-Fronted Woodpecker',
    'Gray Butcherbird',
    'Beautiful Firetail',
    'Wonga Pigeon',
    'Double-Barred Finch',
    'Diamond Firetail',
    'Peaceful Dove',
    'Silvereye',
    'Toucan',
    'Apostlebird',
    'Mulga Parrot',
    'Red-capped Parrot',
    'Rufous-tailed scrub robin',
    'Iberian Green Woodpecker',
    'Hooded Grosbeak',
    'Western Rosella',
    'Regent Parrot',
    'Ring Ouzel',
    'Satin Bowerbird',
    'Budgerigar',
    'Green Rosella',
    'Red-Tailed Black Cockatoo',
    'Zebra Finch',
    'Woodhoopoe',
    'Rosefinch',
    'Crimson-Collared Grosbeak',
    'Gang-gang Cockatoo',
    'Long-billed Corella',
    'Maghreb Magpie',
    'Red-browed firetail',
    'Cordon-bleu',
    'Red Wattlebird',
    'Pale-Headed Rosella',
    'Hornbill',
    'Euphonia',
    'Yellow-Billed Cardinal',
    'Black-throated Finch',
    'Rock nuthatch',
    'Iberian magpie',
    'Corsican Finch',
    'Common Firecrest',
    'Yellow Grosbeak',
    'Brown-Necked Raven',
    'Mexican Chickadee',
]

export const ALL_BIRDS_SORTED = ALL_BIRDS.sort()
